spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test # 4000 for fedora, 5432 for windows
    driver-class-name: org.postgresql.Driver
    username: user
    password: pass

server:
  port: 3002
  servlet:
    context-path: /v1/restaurant-api

restaurant:
  user-paths:
    - "/restaurant/create"
    - "/restaurant/delete"
    - "/restaurant/save"
    - "/menuItem/create"
    - "/menuItem/delete"
    - "/menu/updateItems"
    - "/menu/create"
    - "/menu/delete"
    - "/menu/info"
    - "/menu/addItem"
    - "/restaurant/addFavorite"
    - "/savedRecipes/delete"
